version: '3'

services:
  nginx:
    image: north-trans-api-nginx:latest
    ports:
      - 80
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
#    environment:
#      - VIRTUAL_HOST=app1
#    networks:
#      - default
#      - web
    volumes:
      - static:/app/static
    depends_on:
      - app
    restart: always

  app:
    image: north-trans-python:latest
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
    volumes:
      - static:/app/static



  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: north-trans
      POSTGRES_USER: north-trans
      POSTGRES_PASSWORD: north-trans
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  static:
