version: '3'

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: north-trans
      POSTGRES_USER: north-trans
      POSTGRES_PASSWORD: north-trans
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
