version: '3'

services:
  app:
    image: north-trans-api:latest
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db



  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: north-trans
      POSTGRES_USER: north-trans
      POSTGRES_PASSWORD: north-trans
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
