[tool.poetry]
name = "drf-north-trans"
version = "0.1.0"
description = ""
authors = ["Juan-Camilo-Suarez <juancamilosuarez3@gmail.com>"]
readme = "README.md"
packages = [{include = "drf_north_trans"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
black = "22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
