# Generated by Django 4.1.3 on 2022-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("city", models.CharField(max_length=120, verbose_name="City")),
                ("email", models.EmailField(max_length=120, verbose_name="Email")),
                ("phone", models.CharField(max_length=120, verbose_name="Phone")),
                (
                    "user_position",
                    models.CharField(
                        choices=[("client", "client"), ("driver", "driver")],
                        max_length=15,
                        verbose_name="Type User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Register",
                "verbose_name_plural": "Applications Register",
            },
        ),
    ]
