# Generated by Django 4.1.3 on 2022-12-25 14:38

from django.db import migrations

# mi migracion para completra los espacio de una fila
def set_role_for_users(apps, schema_editor):
    User = apps.get_model("api", "User")
    User.objects.filter(is_staff=True).update(role="worker")
    User.objects.filter(is_staff=False).update(role="driver")
    User.objects.filter(is_staff=False).update(role="client")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(set_role_for_users),
    ]
