# Generated by Django 4.1.3 on 2022-12-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_clientprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=120, verbose_name="number|")),
                ("model", models.CharField(max_length=120, verbose_name="model")),
                ("capacity", models.IntegerField()),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=120, verbose_name="City")),
                ("phone", models.CharField(max_length=120, verbose_name="Phone")),
                (
                    "Car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
