# Generated by Django 4.1.3 on 2023-02-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_applicationstransport_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationstransport",
            options={},
        ),
    ]
