# Generated by Django 4.1.3 on 2022-12-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("admin", "Администратор")],
                max_length=20,
                null=True,
                verbose_name="role",
            ),
        ),
    ]
