# Generated by Django 4.1.3 on 2022-12-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "client"),
                    ("driver", "driver"),
                    ("worker", "worker"),
                ],
                max_length=20,
                null=True,
                verbose_name="role",
            ),
        ),
    ]
