# Generated by Django 4.1.3 on 2022-12-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20221225_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
