# Generated by Django 4.1.3 on 2022-12-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_car_alter_clientprofile_avatar_driverprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Car", "verbose_name_plural": "Cars"},
        ),
        migrations.AlterModelOptions(
            name="clientprofile",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="driverprofile",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
        migrations.AlterField(
            model_name="car",
            name="capacity",
            field=models.IntegerField(verbose_name="capacity on kg"),
        ),
        migrations.AlterField(
            model_name="car",
            name="number",
            field=models.CharField(max_length=120, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users_avatar/"),
        ),
        migrations.CreateModel(
            name="ApplicationsTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "processing"),
                            ("accepted", "accepted"),
                            ("dismissed", "dismissed"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="role",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("commentary", models.TextField(null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="cars/")),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.clientprofile",
                        verbose_name="client",
                    ),
                ),
                (
                    "driver_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.driverprofile",
                        verbose_name="driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application For Transport",
                "verbose_name_plural": "Applications For Transport",
            },
        ),
    ]
