# Generated by Django 4.1.3 on 2022-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_car_options_alter_clientprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationstransport",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="applications/"),
        ),
    ]
