# Generated by Django 4.1.3 on 2022-12-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_applicationstransport_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationstransport",
            name="invoice",
            field=models.ImageField(
                blank=True, null=True, upload_to="applications/invoice"
            ),
        ),
        migrations.AlterField(
            model_name="applicationstransport",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="applicationstransport",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("accepted", "accepted"),
                    ("dismissed", "dismissed"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="Car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.car",
                verbose_name="Car",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
