# Generated by Django 4.1.3 on 2022-12-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_applicationstransport_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationstransport",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "processing"),
                    ("accepted", "accepted"),
                    ("dismissed", "dismissed"),
                ],
                default="processing",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
